# Generated by Django 5.2 on 2025-05-04 16:03

import food_info.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_info", "0002_rename_carbs_fooditem_carbs_per_100g_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="ean",
            field=models.IntegerField(validators=[food_info.models.validate_ean]),
        ),
        migrations.AlterField(
            model_name="fooditem",
            name="weight",
            field=models.FloatField(),
        ),
    ]
