# Generated by Django 5.2 on 2025-05-05 14:50

import food_info.barcode
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("food_info", "0004_delete_items_with_duplicate_eans"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fooditem",
            name="ean",
            field=models.IntegerField(
                unique=True, validators=[food_info.barcode.validate_ean]
            ),
        ),
    ]
